name: my_church
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1 # Added a build number

environment:
  sdk: '>=3.0.0 <4.0.0' # Changed to a more common and recommended range

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  uuid: ^4.3.1
  firebase_data_connect: ^0.1.3+2
  firebase_database: ^11.1.6
  googleapis: ^11.4.0
  googleapis_auth: ^1.3.0
  url_launcher: ^6.1.14  # ✅ Opens YouTube links in browser/app
  youtube_player_flutter: ^9.1.1  # ✅ Plays YouTube videos inside the app
  youtube_player_iframe: ^4.0.4
  sqlite3_flutter_libs: ^0.5.31  # ✅ Native SQLite support
  pdf: ^3.11.3
  printing: ^5.14.2
  shimmer: ^3.0.0
  open_file: ^3.5.10  # To Open Generated PDF Receipt
  share_plus: ^10.1.4  # To Share the PDF Receipt
  sqflite: ^2.4.2 # Latest version
  sqflite_common_ffi: ^2.3.2
  convert: ^3.1.1
  ffi: ^2.1.2
  shared_preferences_web: ^2.4.3  # ✅ Web Support
  flutter_secure_storage: ^9.2.4
  path: ^1.9.1  # Use the latest version from pub.dev
  path_provider: ^2.1.5  # Helps find database location
  http: ^1.3.0
  photo_view: ^0.15.0    # For full image controls (zoom, pan, rotate)
  fluttertoast: ^8.2.12        # Optional: For better toast messages
  google_fonts: ^6.2.1
  accordion: ^2.6.0
  font_awesome_flutter: ^10.8.0
  file_picker: ^9.2.0   # For selecting audio files
  video_player: ^2.9.3
  timeago: ^3.7.0
  intl: ^0.19.0 # Correctly added and indented
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flip_card: ^0.7.0
  video_compress: ^3.1.4
  chewie: ^1.11.0            # Advanced video player with controls
    # 1️⃣ Audio Playback & Streaming
  just_audio: ^0.9.46   # For playing local & network audio
  just_audio_background: ^0.0.1-beta.15  # Background playback support
  audio_service: ^0.18.17   # Background audio service
    # 2️⃣ State Management
  provider: ^6.1.2   # State management (alternative: riverpod)
    # 4️⃣ UI Enhancements
  flutter_bloc: ^9.1.0  # Bloc pattern for state management
  lottie: ^3.3.0  # For animations
  cached_network_image: ^3.4.1  # Cache images (album covers)
    # 6️⃣ Database (For Offline Songs & Playlists)
  hive: ^2.2.3 # Lightweight database alternative
  hive_flutter: ^1.1.0
    # 8️⃣ Permissions (For accessing storage)
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_storage_web: ^3.10.11
  flutter_image_compress: ^2.4.0
  flutter_sound: ^9.0.0
  flutter_gen: ^5.10.0
  sqflite_common_ffi_web: ^1.0.0
  webview_flutter: ^4.4.2
  web: ^1.1.1
  syncfusion_flutter_charts: ^28.2.12
  universal_html: ^2.2.3 # for Web download

flutter_web_plugins:
  sdk: flutter  # ✅ Required for Web support
  js: ^0.6.3  # ✅ Required for Web (IndexedDB support)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated to a more recent version
  flutter_launcher_icons: ^0.14.3  # Latest version
  build_runner: ^2.4.15  # ✅ Required to generate Drift ORM files
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # icon path
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/church.png
    - assets/CSI Christ Church.png
    - assets/gallery.png
    - assets/songs.png
    - assets/video.png
    - assets/bible.png
    - assets/Bible-tamil-main/
    - assets/sothirabaligal.json
    - assets/AKJV.json
    - assets/youtubelogo.png
    - assets/upheld-setting-454612-f1-bd01f9fd2fa2.json
    - assets/Aananthame/
    - assets/audio_files.json
    - assets/csi-st-thomas-church-10292362.png
    - assets/success_tick.json
    - assets/Noto_Sans/
    - assets/Noto_Sans/static/NotoSans-Regular.ttf
    - assets/profile_pic.png
    - assets/ad1.png
    - assets/ad2.png
    - assets/ad3.png
    - assets/ad4.png
    - assets/bibleshop.png
    - assets/songbook.png
    - assets/scarf.png
    - assets/versecards.png