// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg3u9Qn0Ybosg0CO0Kkf72bJR5oj1Ru-I',
    appId: '1:1020032569754:web:0eb70cc100d23ec88bea23',
    messagingSenderId: '1020032569754',
    projectId: 'my-church-14ca6',
    authDomain: 'my-church-14ca6.firebaseapp.com',
    storageBucket: 'my-church-14ca6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBswL5WL6medrYbYrIHfxGhszrNWIfeBQs',
    appId: '1:1020032569754:ios:63e1ec136606c5598bea23',
    messagingSenderId: '1020032569754',
    projectId: 'my-church-14ca6',
    storageBucket: 'my-church-14ca6.firebasestorage.app',
    iosBundleId: 'com.example.myChurch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBswL5WL6medrYbYrIHfxGhszrNWIfeBQs',
    appId: '1:1020032569754:ios:63e1ec136606c5598bea23',
    messagingSenderId: '1020032569754',
    projectId: 'my-church-14ca6',
    storageBucket: 'my-church-14ca6.firebasestorage.app',
    iosBundleId: 'com.example.myChurch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg3u9Qn0Ybosg0CO0Kkf72bJR5oj1Ru-I',
    appId: '1:1020032569754:web:96a27b67549634158bea23',
    messagingSenderId: '1020032569754',
    projectId: 'my-church-14ca6',
    authDomain: 'my-church-14ca6.firebaseapp.com',
    storageBucket: 'my-church-14ca6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHd-V_yx_gZT7ZROMXpsipv-VRbCp1EDI',
    appId: '1:1020032569754:android:7909789e9c99a8a48bea23',
    messagingSenderId: '1020032569754',
    projectId: 'my-church-14ca6',
    storageBucket: 'my-church-14ca6.firebasestorage.app',
  );

}