const Map<String, String> bookNameMap = {
  // Old Testament
  "ஆதியாகமம்": "Genesis",
  "யாத்திராகமம்": "Exodus",
  "லேவியராகமம்": "Leviticus",
  "எண்ணாகமம்": "Numbers",
  "உபாகமம்": "Deuteronomy",
  "யோசுவா": "Joshua",
  "நியாயாதிபதிகள்": "Judges",
  "ரூத்": "Ruth",
  "1 சாமுவேல்": "1 Samuel",
  "2 சாமுவேல்": "2 Samuel",
  "1 இராஜாக்கள்": "1 Kings",
  "2 இராஜாக்கள்": "2 Kings",
  "1 நாளாகமம்": "1 Chronicles",
  "2 நாளாகமம்": "2 Chronicles",
  "எஸ்றா": "Ezra",
  "நெகேமியா": "Nehemiah",
  "எஸ்தேர்": "Esther",
  "யோபு": "Job",
  "சங்கீதம்": "Psalms",
  "நீதி மொழிகள்": "Proverbs",
  "பிரசங்கி": "Ecclesiastes",
  "உன்னதப்பாட்டு": "Song of Songs",
  "எசாயா": "Isaiah",
  "எரேமியா": "Jeremiah",
  "புலம்பல்": "Lamentations",
  "எசேக்கியேல்": "Ezekiel",
  "தானியேல்": "Daniel",
  "ஓசியா": "Hosea",
  "யோவேல்": "Joel",
  "ஆமோஸ்": "Amos",
  "ஒபதியா": "Obadiah",
  "யோனா": "Jonah",
  "மீக்கா": "Micah",
  "நாகூம்": "Nahum",
  "ஆபக்கூக்": "Habakkuk",
  "செப்பனியா": "Zephaniah",
  "ஆகாய்": "Haggai",
  "சகரியா": "Zechariah",
  "மால்கியா": "Malachi",

  // New Testament
  "மத்தேயு": "Matthew",
  "மாற்கு": "Mark",
  "லூக்கா": "Luke",
  "யோவான்": "John",
  "திருத்தூதர் நிகழ்கள்": "Acts",
  "ரோமர்": "Romans",
  "1 கொரிந்தியர்": "1 Corinthians",
  "2 கொரிந்தியர்": "2 Corinthians",
  "கலாத்தியர்": "Galatians",
  "எபேசியர்": "Ephesians",
  "பிலிப்பியர்": "Philippians",
  "கொலோசெயர்": "Colossians",
  "1 தெசலோனிக்கியர்": "1 Thessalonians",
  "2 தெசலோனிக்கியர்": "2 Thessalonians",
  "1 தீமோத்தேயு": "1 Timothy",
  "2 தீமோத்தேயு": "2 Timothy",
  "தீத்து": "Titus",
  "பிலேமோன்": "Philemon",
  "எபிரேயர்": "Hebrews",
  "யாக்கோபு": "James",
  "1 பேதுரு": "1 Peter",
  "2 பேதுரு": "2 Peter",
  "1 யோவான்": "1 John",
  "2 யோவான்": "2 John",
  "3 யோவான்": "3 John",
  "யூதா": "Jude",
  "வெளிப்படுத்தல்": "Revelation"
};